/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kevincheng_anserialport_SerialPort */

#ifndef _Included_com_kevincheng_anserialport_SerialPort
#define _Included_com_kevincheng_anserialport_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kevincheng_anserialport_SerialPort
 * Method:    nativeOpen
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_kevincheng_anserialport_SerialPort_nativeOpen
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_kevincheng_anserialport_SerialPort
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kevincheng_anserialport_SerialPort_nativeClose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
